name: airplane_mode_checker
description: Flutter plugin allows you to check the status of Airplane Mode on
  iOS and Android mobile.
version: 3.1.0
homepage: https://github.com/14h4i/airplane_mode_checker

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.u14h4i.airplane_mode_checker
        pluginClass: AirplaneModeCheckerPlugin
      ios:
        pluginClass: AirplaneModeCheckerPlugin
